# Generated by Django 5.0.6 on 2024-06-10 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='ruta_archivo',
        ),
        migrations.RemoveField(
            model_name='archivo',
            name='tipo_archivo',
        ),
        migrations.AddField(
            model_name='archivo',
            name='archivo',
            field=models.FileField(default='', upload_to='archivos/'),
            preserve_default=False,
        ),
    ]
