# Generated by Django 5.0.6 on 2024-06-10 23:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_archivo_ruta_archivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grafica',
            name='imagen',
            field=models.ImageField(default='', upload_to='graficas/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grafica',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
