# Generated by Django 5.0.6 on 2024-06-15 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_grafica_imagen_alter_grafica_fecha_creacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grafica',
            old_name='imagen',
            new_name='imagen_grafica',
        ),
    ]
